spring:
  docker:
    compose:
      profiles:
        active: "local"
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    username: user
    password: password # we can use key vault or system variables to store the sensitive information
    url: jdbc:mysql://localhost:3313/restaurant

management:
  tracing:
    enabled: false
