spring:
  docker:
    compose:
      profiles:
        active: "local"
  kafka:
    bootstrap-servers: localhost:29092

  datasource:
    username: user
    password: password # we can use key vault or system variables to store the sensitive information
    url: jdbc:mysql://localhost:3312/order

invoice:
  base:
    uri: http://localhost:8081/api/invoice
