spring:
  application:
    name: order service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      properties:
        "[request.timeout.ms]" : 100
        "[max.block.ms]": 1000 # https://stackoverflow.com/questions/49487619/how-to-set-timeout-for-onfailure-event-spring-kafka
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.assessment.*
        spring.json.type.mapping: "com.assessment.restaurant.dto.RestaurantStatusDetails:com.assessment.order.dto.RestaurantStatusDetails"
# ideally we should have add a kafka health check, but it seems quite challenging. So, for now using the timeout option
    order:
      details:
        topic:
          name: order-details
    restaurant:
      status:
        topic:
          name: restaurant-status

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:order}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password} # we can use key vault or system variables to store the sensitive information

server:
  port: 8080
  servlet:
    context-path: /api

# tracings are sampled 10% of time, but can be configured
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    kafka
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://${TEMPO_HOST:tempo}:${TEMPO_PORT:9411}/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

invoice:
  base:
    uri: http://${RESTAURANT_HOST:localhost}:8081/api/invoice