spring:
  application:
    name: order service
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080
  servlet:
    context-path: /api


