global:
  scrape_interval: 2s
  evaluation_interval: 2s
scrape_configs:
  - job_name: 'app-api'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['local-order-api:8080']
  - job_name: 'user-api'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'local-restaurant-api:8081' ]
